language: java
matrix:
  include:
  - os: linux
  - os: osx
    osx_image: xcode9.1
cache:
  directories:
  - "$HOME/.m2"
script:
- "./build.sh"
env:
  global:
  - secure: KO67t6irlng28KFrUsc2aoBoJJesw9YQpr4VTlWxp8qkLaaMi58G8g3/aOtUPMSwD6b5Dc7ZNjF3VeFzXibZVa6OaZlGVtimGnCZGwQX2L7vpnwvTecEeGzWDdpHSMCHlkhhIPx9i3IuQ4IixghcIl2QNOWUcSg8+rwlMtBVOhUyYjzAssde278LI695CFV8Cz+LhXe61m56+SKzfTyKUTFxmU/kePLpB1vB+qtOYQZbWyH33l1liXKzyvyH4FsTg/CBlInx7qieOyRQ+ZUzJAURQrusCiw3VqBuHmw9vD7e4noiUBrdrff9ioo3STlPTU5lgXEzojXUGYyx0E/cmLEBYbC43mDa9vpGjBRjQCJIWA7Rv1a9ivLgu81LYaNnztbizUwJfZ56TZy27XYkdcP+ArUkfANtziEa6kG3DHitRDF0w6BcHRSGosM5VcS2OsfsS5sfIzADrPF9YmB5j+E5fSVMxlgl7KpKCSv4aCtqCu0VmgsW2l0UyWCNpKRdK3AMcVDFYiv9Yb8rBqnICp9kWtLvVMyljRSCiRlv3obZNfUwPfzGS2UM6WzFV+2mOnrghFP0sxc6sRGtfn2zEleznsNvrgp669Z+n15vT2Uy1lvEEEvI6ZA657oPi3TbMs8MaPIo467cQ51DL/EqKef0HrbSnLHORRIugJFXORc=
  - secure: gLeK/sYikq4Q4wXn3398KrBV4fg4xj5JBxf5vEZazI81oPWPL1OSR6IR50d2e5sOQP3gIGeKEH77+Uop5lKzJDlGv5Sv7oyXw8lFJHJjF+gxD8SE7kxJ4XAj4vhOu4uL+aL/5u0vHvkPLYXwetfX3p3TcHT59F8lhE9iIPpTOBwTRyv8cX3cHfA9aji6WkXzmOWyCcCbFW3DaXznn5njY5lvardlW+3w+/v9DE/6NEjPLgfH6xDRCtAYPD97robfgs4kb4pVyXUF8d2j28G922QvdYbbyUGpou1/vFW/iTSGY9lBTKK4lfU28F7CElBhU6JDeIHVI9xjGZcYIY5DieGKMD+GOfRFgQcu2HQ05avP1CshXlOrVoJTiw02o77vOnWSsurv96LrlZzT0Cwv8WiQP1c/IkailqFiwrLsegqMEicmUafQGH+MdRWTaROjfQj6tHIgis8Ae+iBBam3CrTPXrv2/TCFHZxnvNOIWnZN39ehtNXwRU0VxGRhyUXhvp0WyHsItqhkAq/qrbL5mc4++OcTZ3Fx3eC8n3NWtutymeW9d6YiBK5eCfwtwjdaMSgls4J4l94OSsv5P453P/3zdoDSP6WbJYaKpNnBkEeJoqs/hgEv1UhypGHy2FueXPM4KRax97ZjpwZozzTSnDHnieRmdZfAZ9TZPESF5i0=
